version: "3.1"
services:

  db:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=mobly-test
      - MYSQL_USER=test
      - MYSQL_PASSWORD=password
    ports:
      - 3306:3306

  webserver:
    image: nginx:alpine
    working_dir: /app
    volumes:
        - ./app:/application
        - ./docker/nginx/nginx_dev.conf:/etc/nginx/conf.d/default.conf
    ports:
     - 80:80

  app:
    build: docker/php-fpm
    working_dir: /application
    volumes:
      - ./app:/application

  mailhog:
    image: 'mailhog/mailhog:latest'
    ports:
      - 1025:1025
      - 8025:8025